In [3]:

import pandas as pd
import scipy 
import numpy as np
from scipy import stats


In [4]:
df = pd.read_csv(r"C:\Users\VIRAJ KAMAT\Desktop\Data Science\Assignments\Hypothesis\BuyerRatio.csv")
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

# Chi-Square Test.

<li>Ho= Proportions of Male and Female are same.
<li>Ha= Proportions of Male and Female are not same.

In [5]:
df.columns

Index(['Observed Values', 'East', 'West', 'North', 'South'], dtype='object')

In [6]:
df1 = df.drop(['Observed Values'], axis=1)

In [7]:
df1.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [8]:
observed_values = df1.values
print('Observed Values:- \n', observed_values)

Observed Values:- 
 [[  50  142  131   70]
 [ 435 1523 1356  750]]


In [9]:
val=stats.chi2_contingency(df1)

In [10]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [11]:
Expected_values = val[3]

In [13]:
no_of_rows= len(df1.iloc[0:2,:0])
no_of_columns= len(df1.iloc[0,0:4])
dof=(no_of_rows-1)*(no_of_columns-1)   #finding degrees of freedom
print("Degrees of Freedom:- ", dof)
alpha=0.05


Degrees of Freedom:-  3


In [14]:
from scipy.stats import chi2

chi_square = sum([(o-e)**2./e for o,e in zip(observed_values,Expected_values)])
chi_square_statistic = chi_square[0]+chi_square[1]

In [15]:
print("chi - square_statistic:-" , chi_square_statistic)

chi - square_statistic:- 1.5152956451130446


In [16]:
critical_value = chi2.ppf(q=1-alpha, df=dof) # p_value is aplha so q_value will be 1 - alpha. In this case q is 0.95
print("critical_value:- ", critical_value)


critical_value:-  7.814727903251179


In [17]:
#calculating p_value

p_value = 1-chi2.cdf(x=chi_square_statistic,df=dof)
print('p_value:- ',p_value)
print("significance_level:- ",alpha)
print("Degrees of Freedom:- ",dof)

p_value:-  0.6787446296467897
significance_level:-  0.05
Degrees of Freedom:-  3


In [19]:
#chi_square_statistic is less than critical_value
#p_value is greater than 0.05
#proportion of male and female across regions are same